name: Build All Platforms

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.6.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: ''
        
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        
    - name: Build Executable  
      run: |
        cd build
        cmake --build . --config Release --parallel
        
    - name: Deploy Qt Dependencies
      run: |
        # Create deployment directory
        mkdir deploy
        copy build\bin\Release\GertAutoClicker.exe deploy\
        
        # Find windeployqt.exe in Qt installation
        $qtPath = $env:QT_ROOT_DIR
        if (-not $qtPath) {
          $qtPath = $env:Qt6_DIR + "\..\..\.."
        }
        $windeployqt = "$qtPath\bin\windeployqt.exe"
        
        echo "Qt path: $qtPath"
        echo "Looking for windeployqt at: $windeployqt"
        
        if (Test-Path $windeployqt) {
          echo "Found windeployqt, deploying Qt dependencies..."
          & $windeployqt --release --no-translations --no-system-d3d-compiler --no-opengl-sw deploy\GertAutoClicker.exe
        } else {
          echo "windeployqt not found, searching in PATH..."
          $windeployqtInPath = Get-Command windeployqt.exe -ErrorAction SilentlyContinue
          if ($windeployqtInPath) {
            echo "Found windeployqt in PATH: $($windeployqtInPath.Source)"
            windeployqt.exe --release --no-translations --no-system-d3d-compiler --no-opengl-sw deploy\GertAutoClicker.exe
          } else {
            echo "ERROR: windeployqt.exe not found!"
            echo "Available environment variables:"
            Get-ChildItem env: | Where-Object {$_.Name -match "Qt|QT"} | Format-Table Name, Value
            exit 1
          }
        }
        
        echo "Deployment complete. Contents:"
        Get-ChildItem deploy -Recurse
        
    - name: Create Self-Extracting Portable Executable
      run: |
        # Install 7-Zip for creating self-extracting archive
        choco install 7zip -y
        
        # Create self-extracting executable configuration
        $configFile = @"
;!@Install@!UTF-8!
Title="Gert Auto Clicker - Portable"
BeginPrompt="Extract and run Gert Auto Clicker?"
CancelPrompt="Cancel extraction?"
ExtractDialogText="Extracting Gert Auto Clicker..."
ExtractPathText="Extract to:"
ExtractTitle="Gert Auto Clicker Setup"
GUIFlags="8+32+64+256+4096"
GUIMode="1"
InstallPath="%TEMP%\GertAutoClicker"
OverwriteMode="2"
ExecuteFile="GertAutoClicker.exe"
ExecuteParameters=""
;!@InstallEnd@!
"@
        
        # Save config to file
        $configFile | Out-File -FilePath "config.txt" -Encoding ASCII
        
        # Create archive of all deployed files
        & "C:\Program Files\7-Zip\7z.exe" a -t7z "app.7z" "deploy\*"
        
        # Create self-extracting executable
        cmd /c copy /b "C:\Program Files\7-Zip\7z.sfx" + config.txt + app.7z GertAutoClicker-Portable.exe
        
        echo "Self-extracting portable executable created:"
        Get-ChildItem GertAutoClicker-Portable.exe | Select-Object Name, Length
        
        # Also create the traditional zip for comparison
        Compress-Archive -Path deploy\* -DestinationPath GertAutoClicker-Windows-Bundle.zip
        
    - name: Verify Dependencies
      run: |
        echo "Checking main executable dependencies:"
        if (Get-Command dumpbin -ErrorAction SilentlyContinue) {
          dumpbin /dependents deploy\GertAutoClicker.exe
        } else {
          echo "dumpbin not available, skipping dependency check"
        }
        
    - name: Upload Portable Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: gert-auto-clicker-windows-portable
        path: |
          GertAutoClicker-Portable.exe
          GertAutoClicker-Windows-Bundle.zip

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt6
      run: |
        brew update
        brew install qt@6
        echo "/opt/homebrew/opt/qt@6/bin" >> $GITHUB_PATH
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$(brew --prefix qt@6)"
        
    - name: Build
      run: |
        cd build
        make -j$(sysctl -n hw.ncpu)
        
    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: gert-auto-clicker-macos
        path: build/bin/GertAutoClicker

