name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean

jobs:
  build-all:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            artifact: Release/GertAutoClicker.exe
            archive: gert-auto-clicker-windows.zip
          - os: macos-latest
            name: macos
            artifact: GertAutoClicker
            archive: gert-auto-clicker-macos.zip
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Windows-specific setup
    - name: Install vcpkg (Windows)
      if: matrix.name == 'windows'
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
        
    - name: Install Qt6 Static (Windows)
      if: matrix.name == 'windows'
      timeout-minutes: 60
      run: |
        cd vcpkg
        .\vcpkg install qt6-base:x64-windows-static qt6-widgets:x64-windows-static qt6-gui:x64-windows-static
    
    # macOS-specific setup
    - name: Install Qt6 (macOS)
      if: matrix.name == 'macos'
      run: |
        brew update
        brew install qt@6
        echo "/opt/homebrew/opt/qt@6/bin" >> $GITHUB_PATH
    
    
    # Build configuration
    - name: Configure CMake (Windows)
      if: matrix.name == 'windows'
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC=ON -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static
        
    - name: Configure CMake (macOS)
      if: matrix.name == 'macos'
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$(brew --prefix qt@6)"
        
    
    # Build
    - name: Build (Windows)
      if: matrix.name == 'windows'
      run: |
        cd build
        cmake --build . --config Release
        
    - name: Build (macOS)
      if: matrix.name == 'macos'
      run: |
        cd build
        make -j$(sysctl -n hw.ncpu)
        
    
    # Package executables
    - name: Package executable (Windows)
      if: matrix.name == 'windows'
      run: |
        cd build/bin
        7z a ../../${{ matrix.archive }} ${{ matrix.artifact }}
        
    - name: Package executable (macOS/Linux)
      if: matrix.name != 'windows'
      run: |
        cd build/bin
        zip ../../${{ matrix.archive }} ${{ matrix.artifact }}
    
    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.name }}
        path: ${{ matrix.archive }}

  create-release:
    needs: build-all
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        
    - name: Display structure of downloaded files
      run: ls -la artifacts/
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Gert Auto Clicker ${{ github.event.inputs.version }}
        prerelease: ${{ github.event.inputs.prerelease }}
        generate_release_notes: true
        body: |
          ## Gert Auto Clicker ${{ github.event.inputs.version }}
          
          ### Downloads
          
          - **Windows**: Download `gert-auto-clicker-windows.zip`
          - **macOS**: Download `gert-auto-clicker-macos.zip`
          
          ### Installation
          
          1. Download the appropriate zip file for your platform
          2. Extract the executable
          3. Run the application
          
          ### Platform-specific notes
          
          **Windows**: May require administrator privileges for hotkey functionality
          
          **macOS**: Requires accessibility permissions in System Preferences > Security & Privacy > Privacy > Accessibility
          
          ---
          
          **Full Changelog**: https://github.com/${{ github.repository }}/compare/previous-tag...${{ github.event.inputs.version }}
        files: |
          artifacts/release-windows/gert-auto-clicker-windows.zip
          artifacts/release-macos/gert-auto-clicker-macos.zip